server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location /fingmap/ {
        index index.html;
        try_files $uri $uri/ /fingmap/index.html;
    }

    gzip off;

    location /fingmap/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}